// Auto-generated by dynamic_tool at 2026-06-15T09:45:08.553Z.
// You can edit this file — changes take effect on next call.
export default {
  description: "分析 JS/TS 文件的依赖关系树，输出树形依赖图",
  args: {
  "targetFile": {
    "type": "string",
    "description": "目标文件路径（相对于工作区或绝对路径）"
  },
  "maxDepth": {
    "type": "number",
    "description": "最大递归深度",
    "default": 5
  }
},
  execute: async (args, ctx) => {
    const path = await import("path")
    const fs = await import("fs")
    const root = ctx.worktree || ctx.directory
    const exts = [".ts", ".tsx", ".js", ".jsx"]
    function resolve(f, s) {
      if (!s.startsWith(".")) return null
      const b = path.dirname(f); const c = path.resolve(b, s)
      for (const e of exts) { const p = c + e; if (fs.existsSync(p)) return path.normalize(p) }
      for (const i of ["index.ts","index.js"]) { const p = path.join(c,i); if (fs.existsSync(p)) return path.normalize(p) }
      return null
    }
    function parse(f) {
      try {
        const c = fs.readFileSync(f,"utf-8").slice(0,50000)
        const r = []
        for (const l of c.split("\n").filter(l=>l.length<500)) {
          const m = l.match(/from\s+(["'])([^"']{1,150}?)\1/)
          if (m) r.push(m[2])
        }
        return r
      } catch { return [] }
    }
    const visited = new Set(), edges = new Map()
    function walk(f, d) {
      if (d > args.maxDepth || visited.has(f)) return; visited.add(f)
      for (const s of parse(f).map(s=>resolve(f,s)).filter(Boolean)) {
        if (!edges.has(f)) edges.set(f,[])
        edges.get(f).push(s); walk(s,d+1)
      }
    }
    const abs = path.isAbsolute(args.targetFile) ? args.targetFile : path.resolve(root, args.targetFile)
    if (!fs.existsSync(abs)) return `❌ File not found: ${args.targetFile}`
    walk(abs, 0); const out = []
    function print(f,i,l,s) {
      if (s.has(f)) { out.push(`${i}${l?"└── ":"├── "}${path.relative(root,f)} 🔄`); return }
      s.add(f); out.push(`${i}${l?"└── ":"├── "}${path.relative(root,f)}`)
      const c = edges.get(f)||[]
      for (let j=0;j<c.length;j++) print(c[j],`${i}${l?"    ":"│   "}`,j===c.length-1,new Set(s))
    }
    print(abs,"",true,new Set())
    return `📦 ${path.relative(root,abs)}\n${out.join("\n")}\n\n${visited.size} files`
  },
}
